# Generated by Django 3.2.21 on 2023-10-05 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp4', '0002_contact_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='contact',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
